import { get, set, del, createStore } from 'idb-keyval'
import type { AssetId, CollageDoc, ImageAsset } from '@/types'
import {
  isTauri,
  saveFileDialog,
  openFileDialog,
  readTextFile,
  writeTextFile,
  readImageInfo,
  writeFile,
  readFile,
} from '@/lib/tauri'

/**
 * Cross-platform persistence.
 *
 * Browser: IndexedDB via idb-keyval (same as before).
 * Tauri: file system via Rust backend.
 *
 * The code checks `isTauri()` at runtime and dispatches accordingly.
 * During development (browser), it uses IndexedDB; in the desktop app,
 * it reads/writes files directly to disk via @tauri-apps/plugin-fs.
 */

// ── browser-only IndexedDB stores ────────────────────────────────────────────

const docStore = !isTauri() ? createStore('ultra-collage', 'documents') : null
const blobStore = !isTauri() ? createStore('ultra-collage-blobs', 'blobs') : null

const CURRENT_DOC_KEY = 'current'

// ── Project directory (Tauri only) ───────────────────────────────────────────

/**
 * In Tauri, we store projects in a dedicated folder:
 *   Documents/UltraCollage/
 * Each project is a folder with:
 *   project.json  (the CollageDoc, assets metadata only)
 *   assets/       (raw image files copied from their source)
 */

async function ensureProjectDir(): Promise<string> {
  const { join } = await import('@tauri-apps/api/path')
  const { mkdir, exists } = await import('@tauri-apps/plugin-fs')
  const docsDir = await join(await (await import('@tauri-apps/api/path')).documentDir(), 'UltraCollage')
  if (!(await exists(docsDir))) {
    await mkdir(docsDir)
  }
  return docsDir
}

// ── blobs (browser: IndexedDB | Tauri: disk files) ───────────────────────────

/** In Tauri, images are referenced by their original file path. */
interface TauriAsset extends Omit<ImageAsset, 'url'> {
  /** Absolute path to the source image file on disk. */
  filePath: string
}

export async function putBlob(id: AssetId, blob: Blob): Promise<void> {
  if (isTauri()) {
    // In Tauri, we don't store blobs in IndexedDB.
    // Images are kept at their source path; thumbnails are generated by Rust.
    // This is a no-op for the initial save; the image path is stored in the asset.
    return
  }
  await set(id, blob, blobStore!)
}

export async function getBlob(id: AssetId): Promise<Blob | undefined> {
  if (isTauri()) return undefined // Not used in Tauri mode
  return get<Blob>(id, blobStore!)
}

export async function deleteBlob(id: AssetId): Promise<void> {
  if (isTauri()) return
  await del(id, blobStore!)
}

// ── document ──────────────────────────────────────────────────────────────────

/** Serializable form of an asset: drop the runtime object URL. */
type StoredAsset = Omit<ImageAsset, 'url'> &
  (TauriAsset extends Record<string, unknown> ? { filePath?: string } : {})

interface StoredDoc extends Omit<CollageDoc, 'assets'> {
  assets: Record<AssetId, StoredAsset>
}

export async function saveDoc(doc: CollageDoc): Promise<void> {
  const stored: StoredDoc = {
    ...doc,
    updatedAt: Date.now(),
    assets: Object.fromEntries(
      Object.entries(doc.assets).map(([id, a]) => {
        const { url: _url, ...rest } = a
        return [id, rest]
      }),
    ),
  }

  if (isTauri()) {
    // Save to project file
    const docsDir = await ensureProjectDir()
    const path = await (await import('@tauri-apps/api/path')).join(docsDir, 'autosave.collage.json')
    await writeTextFile(path, JSON.stringify(stored, null, 2))
    return
  }

  await set(CURRENT_DOC_KEY, stored, docStore!)
}

/** Load the persisted document and re-create object URLs from stored blobs. */
export async function loadDoc(): Promise<CollageDoc | null> {
  if (isTauri()) {
    try {
      const docsDir = await ensureProjectDir()
      const path = await (await import('@tauri-apps/api/path')).join(docsDir, 'autosave.collage.json')
      const text = await readTextFile(path)
      const stored = JSON.parse(text) as StoredDoc
      return rehydrate(stored)
    } catch {
      return null
    }
  }

  const stored = await get<StoredDoc>(CURRENT_DOC_KEY, docStore!)
  if (!stored) return null
  return rehydrate(stored)
}

async function rehydrate(stored: StoredDoc): Promise<CollageDoc> {
  const assets: Record<AssetId, ImageAsset> = {}
  for (const [id, a] of Object.entries(stored.assets)) {
    if (isTauri() && 'filePath' in a && a.filePath) {
      // In Tauri, create object URL from the file path via convertFileSrc
      const { convertFileSrc } = await import('@tauri-apps/api/core')
      const tauriAsset = a as unknown as TauriAsset
      assets[id] = {
        ...a,
        url: convertFileSrc(tauriAsset.filePath),
      }
    } else {
      const blob = await getBlob(id)
      assets[id] = { ...a, url: blob ? URL.createObjectURL(blob) : '' }
    }
  }
  return { ...stored, assets }
}

// ── project import / export (portable single file) ────────────────────────────

interface ProjectFile {
  format: 'ultra-collage'
  version: 1
  doc: StoredDoc
  blobs: Record<AssetId, string> // data URLs
}

const blobToDataURL = (blob: Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const r = new FileReader()
    r.onload = () => resolve(r.result as string)
    r.onerror = reject
    r.readAsDataURL(blob)
  })

const dataURLToBlob = async (dataUrl: string): Promise<Blob> => (await fetch(dataUrl)).blob()

export async function exportProject(doc: CollageDoc): Promise<Blob> {
  const blobs: Record<AssetId, string> = {}
  for (const id of Object.keys(doc.assets)) {
    const blob = await getBlob(id)
    if (blob) blobs[id] = await blobToDataURL(blob)
  }
  const project: ProjectFile = {
    format: 'ultra-collage',
    version: 1,
    doc: {
      ...doc,
      assets: Object.fromEntries(
        Object.entries(doc.assets).map(([id, a]) => {
          const { url: _url, ...rest } = a
          return [id, rest]
        }),
      ),
    },
    blobs,
  }
  return new Blob([JSON.stringify(project)], { type: 'application/json' })
}

export async function importProject(file: File): Promise<CollageDoc> {
  const project = JSON.parse(await file.text()) as ProjectFile
  if (project.format !== 'ultra-collage') throw new Error('Not an Ultra Collage project file')
  // Restore blobs into IndexedDB and re-create object URLs.
  for (const [id, dataUrl] of Object.entries(project.blobs)) {
    const blob = await dataURLToBlob(dataUrl)
    await putBlob(id, blob)
  }
  return rehydrate(project.doc)
}

// ── Tauri-specific: ingest a file from disk into the collage ─────────────────

export async function ingestFileToAsset(filePath: string): Promise<{
  id: AssetId
  asset: ImageAsset
  blob: Blob | null
} | null> {
  try {
    const info = await readImageInfo(filePath)
    const fileName = filePath.split(/[\\/]/).pop() || 'image'
    const id = (await import('@/lib/id')).newId('img')

    // Read the raw file bytes
    const bytes = await readFile(filePath)
    const blob = new Blob([bytes as BlobPart], { type: info.mime })
    const url = URL.createObjectURL(blob)

    const asset: ImageAsset = {
      id,
      name: fileName,
      width: info.width,
      height: info.height,
      url,
      mime: info.mime,
      size: bytes.byteLength,
    }

    return { id, asset, blob }
  } catch (err) {
    console.error('Failed to ingest file:', filePath, err)
    return null
  }
}

// ── Tauri-specific: open project / save project via dialogs ──────────────────

export async function openProjectFromDisk(): Promise<CollageDoc | null> {
  if (!isTauri()) return null

  const result = await openFileDialog({
    filters: [{ name: 'Ultra Collage Project', extensions: ['collage.json'] }],
  })
  if (!result || result.length === 0) return null

  const text = await readTextFile(result[0])
  const project = JSON.parse(text) as StoredDoc
  return rehydrate(project)
}

export async function saveProjectToDisk(doc: CollageDoc): Promise<boolean> {
  if (!isTauri()) return false

  const stored: StoredDoc = {
    ...doc,
    updatedAt: Date.now(),
    assets: Object.fromEntries(
      Object.entries(doc.assets).map(([id, a]) => {
        const { url: _url, ...rest } = a
        return [id, rest]
      }),
    ),
  }

  const path = await saveFileDialog({
    defaultPath: `${(doc.name || 'collage').replace(/[^\w\-]+/g, '_')}.collage.json`,
    filters: [{ name: 'Ultra Collage Project', extensions: ['collage.json'] }],
  })
  if (!path) return false

  await writeTextFile(path, JSON.stringify(stored, null, 2))
  return true
}

export async function exportImageToDisk(
  canvas: HTMLCanvasElement,
  opts: { format: 'png' | 'jpeg'; quality: number; name: string },
): Promise<boolean> {
  if (!isTauri()) return false

  const ext = opts.format === 'png' ? 'png' : 'jpg'
  const path = await saveFileDialog({
    defaultPath: `${(opts.name || 'collage').replace(/[^\w\-]+/g, '_')}.${ext}`,
    filters: [
      { name: 'PNG Image', extensions: ['png'] },
      { name: 'JPEG Image', extensions: ['jpg', 'jpeg'] },
    ],
  })
  if (!path) return false

  const mime = opts.format === 'png' ? 'image/png' : 'image/jpeg'
  const blob = await new Promise<Blob>((resolve, reject) =>
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error('toBlob failed'))),
      mime,
      opts.quality,
    ),
  )

  const buf = await blob.arrayBuffer()
  await writeFile(path, new Uint8Array(buf))
  return true
}
